// <auto-generated />
using CarShowroom.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarShowroom.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20210626063938_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarShowroom.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarPower")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CarRegistration")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductionDate")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
